### PR TITLE
Support commas as delimiter

### PR DESCRIPTION
**Pull request by galkowskit**
Adds simple support for:

```
const x = money.floatToAmount('12,2') // "12.20"
```

Added mostly for supporting inputs in locales like Polish that use comma (`,`) instead of dot (`.`) for decimal delimiter (eg. 12,23 instead of 12.23).

### CODE REVIEW

**Comment by ikr** [comment]
Hi @galkowskit 

I'm sorry, I don't think it belongs here. `floatToAmount` isn't supposed to take string inputs anyway. It's really made for JS floats.

In general, I kind of regret including the `format` helper into the lib. It should have probably been a separate module.

**Comment by galkowskit** [comment]
Eh, too bad. What would be the "correct" way to go for handling user input from the browser? It can be either `,` or `.`. Separate it into different helper function and then pass it to `money-math`?

**Comment by ikr** [comment]
I guess, use whatever you'd use to get a JS float from `'12,2'` string, and then pipe that float into money.floatToAmount.

**Comment by ikr** [comment]
```js
function parseLocalFloat(num) {
    return +(num.replace(",", "."));
}
```

**Pull request closed without merging**
