### PR TITLE
add type definition

### PR DESCRIPTION
**Pull request by taoqf**

### CODE REVIEW

**Comment by ikr** [comment]
Hi @taoqf

Thanks for your efforts. In my opinion, though, in order to bring type safety to money-math, it would require some conceptual planning. Just keeping everything "stringly typed", as this PR suggests, is not enough. On that level, adding a separate .d.ts type definition, leaving the current code as-is would be more adequate.

Do you understand my concerns?

Cheers
Ivan

**Comment by taoqf** [comment]
Sorry for my poor English. I tried to add @types/money-math, but I found this lib doesn't support amd. so I rewrote it in typescript. and use webpack build a bundled js file as I did [here](https://cdn.jsdelivr.net/npm/@taoqf/money-math@3.0.2/dist/) .

**Comment by ikr** [comment]
I'd suggest only adding the AMD support, and a .d.ts file with types definitions as-is, without a full rewrite.

However, in the future, I do want to consider rewriting money-math in TypeScript, with proper type safety guarantees. That won't be just strings flying around then :)

**Comment by taoqf** [comment]
Can't wait.

**Pull request closed without merging**
